# Generated by Django 4.2.18 on 2025-01-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
